#!/bin/bash
################################################################################
######################## Microway Cluster Management Software (MCMS) for OpenHPC
################################################################################
#
# Copyright (c) 2015-2016 by Microway, Inc.
#
# This file is part of Microway Cluster Management Software (MCMS) for OpenHPC.
#
#    MCMS for OpenHPC is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    MCMS for OpenHPC is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with MCMS.  If not, see <http://www.gnu.org/licenses/>
#
################################################################################


################################################################################
#
# Ensures public-key logins for the slurm user can only run allowed commands:
#   * long-running health check script
#   * power off idle nodes
#   * check availability of node (by echoing a newline)
#
################################################################################


rejection_message="The provided SSH key does not have permission to execute these commands."

case "$SSH_ORIGINAL_COMMAND" in
*\&*)
echo $rejection_message
;;
*\(*)
echo $rejection_message
;;
*\{*)
echo $rejection_message
;;
*\;*)
echo $rejection_message
;;
*\<*)
echo $rejection_message
;;
*\`*)
echo $rejection_message
;;
*\|*)
echo $rejection_message
;;
/etc/slurm/scripts/slurm.healthcheck_long)
/etc/slurm/scripts/slurm.healthcheck_long
;;
/sbin/poweroff)
/sbin/poweroff
;;
echo)
echo
;;
*)
echo $rejection_message
;;
esac
